#!/usr/bin/env python3
"""Run 2.2: calculate/download and plot a DEM from the Run 2.1 burst inventory."""

from __future__ import annotations
import argparse
import math
import os
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path


def args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read data_burst/burst_SAFE_inventory.tsv generated by Run 2.1, "
            "calculate the common burst-stack bounds, and optionally call "
            "GMTSAR make_dem.csh, then use GMT to plot the DEM as PDF."
        )
    )
    parser.add_argument(
        "mode",
        nargs="?",
        choices=("1", "2"),
        help="1=calculate/save region only; 2=also run make_dem.csh",
    )
    parser.add_argument(
        "--inventory",
        default="data_burst/burst_SAFE_inventory.tsv",
        help="Run 2.1 inventory (default: data_burst/burst_SAFE_inventory.tsv)",
    )
    parser.add_argument("--topo-dir", default="topo", help="DEM output directory (default: topo)")
    parser.add_argument(
        "--margin", type=float, default=0.2, help="outward margin in degrees (default: 0.2)"
    )
    parser.add_argument(
        "--resolution", type=int, default=1, help="make_dem.csh resolution mode (default: 1)"
    )
    return parser.parse_args()


def show_run_guide() -> None:
    script = Path(sys.argv[0]).name
    print(
        f"""========================================
Run 2.2: prepare burst DEM (processing NOT started)

Input from Run 2.1:
  data_burst/burst_SAFE_inventory.tsv

Mode 1 - preview/calculate the DEM region only:
  ./{script} 1

  Actions:
    1. Read every burst annotation XML listed by Run 2.1.
    2. Show/save the actual west/east/south/north bounds from the XML files.
    3. Show/save the bounds after adding a 0.2-degree margin on all sides.
    4. Round the margin bounds outward to 0.1 degree for make_dem.csh.
    5. Do NOT run make_dem.csh and do NOT download a DEM.

Mode 2 - calculate the region and generate the DEM:
  ./{script} 2

  Additional action:
    Run: make_dem.csh WEST EAST SOUTH NORTH 1
    Plot: topo/dem.grd -> topo/dem.pdf (GMT shaded-relief map)

  Expected outputs:
    topo/dem_region_actual.txt
    topo/dem_region_margin.txt
    topo/dem_region.txt
    topo/dem.grd
    topo/make_dem.log
    topo/dem.pdf
    topo/plot_dem.log

Optional examples:
  ./{script} 1 --margin 0.3
  ./{script} 2 --margin 0.3 --resolution 1
  ./{script} 1 --inventory /other/path/burst_SAFE_inventory.tsv

Recommended workflow:
  1. Run Mode 1 and inspect topo/dem_region.txt.
  2. If the region is suitable, run Mode 2.
========================================
[INFO] No XML was read, no directory/file was created, and no DEM was downloaded."""
    )


def bounds(xml: Path) -> tuple[float, float, float, float]:
    lon: list[float] = []
    lat: list[float] = []
    for _, element in ET.iterparse(xml, events=("end",)):
        if element.tag.rsplit("}", 1)[-1] != "geolocationGridPoint":
            continue
        values = {child.tag.rsplit("}", 1)[-1]: child.text for child in element}
        if values.get("longitude") and values.get("latitude"):
            lon.append(float(values["longitude"])); lat.append(float(values["latitude"]))
        element.clear()
    if not lon:
        raise ValueError(f"no geolocation points: {xml}")
    return min(lon), max(lon), min(lat), max(lat)


def read_inventory(path: Path) -> list[Path]:
    if not path.is_file():
        raise SystemExit(f"[ERROR] missing {path}; complete Run 2.1 formal mode first")
    lines = path.read_text().splitlines()
    if not lines:
        raise SystemExit(f"[ERROR] empty inventory: {path}")
    header = lines[0].split("\t")
    required = ("date", "satellite", "swath", "polarization", "safe", "xml")
    if tuple(header) != required:
        raise SystemExit(
            f"[ERROR] unexpected inventory header in {path}; expected: " + "\\t".join(required)
        )
    xmls: list[Path] = []
    dates: set[str] = set()
    for number, line in enumerate(lines[1:], 2):
        if not line.strip():
            continue
        fields = line.split("\t")
        if len(fields) != len(required):
            raise SystemExit(f"[ERROR] malformed inventory line {number}: {line}")
        date, xml_value = fields[0], fields[5]
        if date in dates:
            raise SystemExit(f"[ERROR] duplicate acquisition date in inventory: {date}")
        dates.add(date)
        xml = Path(xml_value)
        if not xml.is_file() or xml.stat().st_size == 0:
            raise SystemExit(f"[ERROR] missing or empty annotation XML: {xml}")
        xmls.append(xml)
    if len(xmls) < 2:
        raise SystemExit("[ERROR] at least two burst annotation XML files are required")
    return xmls


def plot_dem(topo: Path, gmt: str) -> Path:
    """Render dem.grd as a shaded-relief PDF with GMT modern mode."""
    pdf = topo / "dem.pdf"
    log = topo / "plot_dem.log"
    commands = (
        [gmt, "begin", "dem", "pdf"],
        [
            gmt,
            "grdimage",
            "dem.grd",
            "-JM15c",
            "-Cgeo",
            "-I+d",
            "-Baf",
            "-BWSen+tBurst DEM",
        ],
        [
            gmt,
            "colorbar",
            "-Cgeo",
            "-DjBC+w10c/0.4c+o0c/0.9c+h",
            "-Bxaf+lElevation",
            "-By+lm",
        ],
        [gmt, "end"],
    )
    with tempfile.TemporaryDirectory(prefix=".gmt-user-", dir=topo) as gmt_user:
        environment = os.environ.copy()
        environment["GMT_USERDIR"] = gmt_user
        with log.open("w") as stream:
            for command in commands:
                stream.write("[RUN] " + " ".join(command) + "\n")
                stream.flush()
                result = subprocess.run(
                    command,
                    cwd=topo,
                    env=environment,
                    stdout=stream,
                    stderr=subprocess.STDOUT,
                )
                if result.returncode:
                    raise SystemExit(f"[ERROR] GMT DEM plotting failed; inspect {log}")
    if not pdf.is_file() or pdf.stat().st_size == 0:
        raise SystemExit(f"[ERROR] GMT finished but did not create {pdf}; inspect {log}")
    return pdf


def main() -> int:
    opt = args()
    if opt.mode is None:
        show_run_guide()
        return 0
    if opt.margin < 0:
        raise SystemExit("[ERROR] --margin cannot be negative")
    if opt.resolution < 1:
        raise SystemExit("[ERROR] --resolution must be positive")
    root = Path.cwd().resolve()
    if not (root.name.startswith("T") and any(character.isdigit() for character in root.name)):
        raise SystemExit(f"[ERROR] run in a T-number track directory (current: {root})")
    inventory = Path(opt.inventory).expanduser()
    if not inventory.is_absolute():
        inventory = root / inventory
    inventory = inventory.resolve()
    xmls = read_inventory(inventory)
    try:
        all_bounds = [bounds(path) for path in xmls]
    except (ET.ParseError, OSError, ValueError) as exc:
        raise SystemExit(f"[ERROR] failed to read burst annotation: {exc}") from exc
    actual_west = min(x[0] for x in all_bounds)
    actual_east = max(x[1] for x in all_bounds)
    actual_south = min(x[2] for x in all_bounds)
    actual_north = max(x[3] for x in all_bounds)

    margin_west = actual_west - opt.margin
    margin_east = actual_east + opt.margin
    margin_south = actual_south - opt.margin
    margin_north = actual_north + opt.margin

    west = math.floor(margin_west * 10) / 10
    east = math.ceil(margin_east * 10) / 10
    south = math.floor(margin_south * 10) / 10
    north = math.ceil(margin_north * 10) / 10
    topo_value = Path(opt.topo_dir).expanduser()
    topo = (root / topo_value).resolve() if not topo_value.is_absolute() else topo_value.resolve()
    topo.mkdir(parents=True, exist_ok=True)
    actual_region = topo / "dem_region_actual.txt"
    margin_region = topo / "dem_region_margin.txt"
    region = topo / "dem_region.txt"
    actual_region.write_text(
        f"{actual_west:.8f} {actual_east:.8f} {actual_south:.8f} {actual_north:.8f}\n"
    )
    margin_region.write_text(
        f"{margin_west:.8f} {margin_east:.8f} {margin_south:.8f} {margin_north:.8f}\n"
    )
    region.write_text(f"{west} {east} {south} {north}\n")
    print("========================================")
    print("Run 2.2 burst DEM region")
    print("Order: WEST EAST SOUTH NORTH")
    print(
        "[ACTUAL XML] "
        f"{actual_west:.8f} {actual_east:.8f} {actual_south:.8f} {actual_north:.8f}"
    )
    print(
        f"[+/- {opt.margin:g} DEG] "
        f"{margin_west:.8f} {margin_east:.8f} {margin_south:.8f} {margin_north:.8f}"
    )
    print(f"[FINAL 0.1 DEG] {west:.1f} {east:.1f} {south:.1f} {north:.1f}")
    print("========================================")
    print(f"[XML] {len(xmls)} burst annotations")
    print(f"[INVENTORY] {inventory}")
    print(f"[SAVED ACTUAL] {actual_region}")
    print(f"[SAVED MARGIN] {margin_region}")
    print(f"[SAVED FINAL] {region}")
    command_preview = (
        f"make_dem.csh {west:.1f} {east:.1f} {south:.1f} {north:.1f} {opt.resolution}"
    )
    print(f"[COMMAND PREVIEW] {command_preview}")
    print("[GMT PLOT PREVIEW]")
    print("  gmt begin dem pdf")
    print("  gmt grdimage dem.grd -JM15c -Cgeo -I+d -Baf '-BWSen+tBurst DEM'")
    print(
        "  gmt colorbar -Cgeo -DjBC+w10c/0.4c+o0c/0.9c+h "
        "'-Bxaf+lElevation' -By+lm"
    )
    print("  gmt end")
    print(f"[GMT PDF] {topo / 'dem.pdf'}")
    if opt.mode == "1":
        print("[NOT RUN] The make_dem.csh command above was displayed only.")
        print("[NOT RUN] The GMT commands above were displayed only.")
        print("[DONE] Region comparison saved; DEM was not downloaded")
        return 0
    command = shutil.which("make_dem.csh")
    if command is None:
        raise SystemExit("[ERROR] make_dem.csh not found")
    log = topo / "make_dem.log"
    print(
        f"[RUN] {command} {west:.1f} {east:.1f} "
        f"{south:.1f} {north:.1f} {opt.resolution}"
    )
    with log.open("w") as stream:
        result = subprocess.run(
            [command, str(west), str(east), str(south), str(north), str(opt.resolution)],
            cwd=topo,
            stdout=stream,
            stderr=subprocess.STDOUT,
        )
    if result.returncode or not (topo / "dem.grd").is_file():
        raise SystemExit(f"[ERROR] make_dem failed; inspect {log}")
    gmt = shutil.which("gmt")
    if gmt is None:
        raise SystemExit(
            f"[ERROR] DEM created at {topo / 'dem.grd'}, but GMT was not found; "
            "cannot create dem.pdf"
        )
    print(f"[RUN GMT] Plot shaded DEM PDF from {topo / 'dem.grd'}")
    pdf = plot_dem(topo, gmt)
    print(f"[DONE DEM] {topo / 'dem.grd'}")
    print(f"[DONE PDF] {pdf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
