#!/usr/bin/env bash
# Run 4.4: geocode the SBAS velocity grid and generate KML products.
# Modified by Xin Wang, USTC, Hefei, China
# Last updated: August 14, 2026

set -euo pipefail
export LC_ALL=C LANG=C LANGUAGE=C

SBAS_DIR="sbas_demcorr_pin"
FILTER_METERS=400
CPT_MIN="${VEL_CPT_MIN:--10}"
CPT_MAX="${VEL_CPT_MAX:-10}"
CPT_STEP="${VEL_CPT_STEP:-1}"

die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

usage() {
cat <<'USAGE'
Run 4.4: geocode the SBAS velocity grid and generate PDF/KML products

Check only (no files are created or modified):
  ./run4.4_geocode_sbas_velocity.sh

Formal run with the recommended 400 m spatial filter:
  ./run4.4_geocode_sbas_velocity.sh 1

Default color range:
  -10 to 10, interval 1

Optional environment variables:
  VEL_CPT_MIN=-10 VEL_CPT_MAX=10 VEL_CPT_STEP=1

Main outputs in sbas_demcorr_pin/:
  vel_ll.grd              geographic velocity using the 400 m filter
  vel_ll.cpt              color palette
  vel_ll.pdf              GMT velocity map
  vel_ll.kml and associated KML image files generated by grd2kml.csh
  run4.4_complete         completion record
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then usage; exit 0; fi
(( $# <= 1 )) || die "expected no arguments, or mode 1"
[[ $# -eq 0 || "$1" == "1" ]] || die "MODE must be 1"

for value_name in CPT_MIN CPT_MAX CPT_STEP; do
    value="${!value_name}"
    awk -v x="$value" 'BEGIN { exit !(x ~ /^[-+]?[0-9]*\.?[0-9]+$/) }' ||
        die "$value_name must be numeric (current: $value)"
done
awk -v lo="$CPT_MIN" -v hi="$CPT_MAX" -v step="$CPT_STEP" \
    'BEGIN { exit !(lo < hi && step > 0) }' ||
    die "color range must satisfy MIN < MAX and STEP > 0"

ROOT="$(pwd -P)"
TRACK="$(basename -- "$ROOT")"
[[ "$TRACK" =~ ^T[0-9]+$ ]] || die "run this script in a T-number track directory (current: $ROOT)"
[[ -d "$SBAS_DIR" ]] || die "cannot find $SBAS_DIR/"
[[ -s "$SBAS_DIR/vel.grd" ]] || die "missing or empty: $SBAS_DIR/vel.grd; confirm Run 4.3 finished successfully"
[[ -s "merge/trans.dat" ]] || die "missing or empty: merge/trans.dat"

TRANS_BYTES="$(wc -c < merge/trans.dat | tr -d ' ')"
(( TRANS_BYTES >= 20 * 1024 * 1024 )) ||
    die "merge/trans.dat is smaller than 20 MiB ($TRANS_BYTES bytes); it may be an empty preview placeholder"

for command_name in proj_ra2ll.csh grd2kml.csh gmt; do
    command -v "$command_name" >/dev/null 2>&1 || die "$command_name not found in PATH"
done

GAUSS_NAME="gauss_400"
FIRST_INTF_DIR="$(find F1/intf_all -mindepth 1 -maxdepth 1 -type d \
    -name '20*_20*' -print 2>/dev/null | sort | head -n 1)"
[[ -n "$FIRST_INTF_DIR" ]] || die "cannot find F1/intf_all/20*_20* interferogram directories"
GAUSS_SOURCE="$ROOT/$FIRST_INTF_DIR/$GAUSS_NAME"
[[ -e "$GAUSS_SOURCE" ]] ||
    die "the first interferogram directory lacks $GAUSS_NAME: $FIRST_INTF_DIR"
[[ -s "$GAUSS_SOURCE" ]] || die "filter file is missing or empty: $GAUSS_SOURCE"

echo "========================================"
echo "Run 4.4 input check"
echo "Track root          : $ROOT"
echo "SBAS directory      : $SBAS_DIR"
echo "Radar velocity      : $SBAS_DIR/vel.grd"
echo "Projection table    : merge/trans.dat ($(awk -v b="$TRANS_BYTES" 'BEGIN{printf "%.1f MiB", b/1048576}'))"
echo "Filter distance     : $FILTER_METERS m"
echo "Filter source       : $GAUSS_SOURCE"
echo "Color range         : $CPT_MIN / $CPT_MAX / $CPT_STEP"
echo "PDF/KML source grid : $SBAS_DIR/vel_ll.grd"
echo "========================================"

if (( $# == 0 )); then
    usage
    echo "[CHECK ONLY] No links, geographic grids, CPT, PDF or KML files were created."
    exit 0
fi

cd "$SBAS_DIR"
echo "[CLEAN] Remove previous Run 4.4 products before regeneration"
rm -rf trans.dat "$GAUSS_NAME" vel_ll.grd vel_ll.cpt vel_ll.pdf \
    vel_ll.kml vel_ll.kmz vel_ll.png vel_ll.legend.png vel_ll run4.4_complete

ln -s ../merge/trans.dat trans.dat
ln -s "$GAUSS_SOURCE" "$GAUSS_NAME"

echo "[STEP 1] Project vel.grd using the ${FILTER_METERS} m spatial filter"
proj_ra2ll.csh trans.dat vel.grd vel_ll.grd "$FILTER_METERS"
[[ -s vel_ll.grd ]] || die "vel_ll.grd was not generated"

echo "[STEP 2] Create the velocity color palette"
gmt makecpt -Cjet -T"${CPT_MIN}/${CPT_MAX}/${CPT_STEP}" -Z -D > vel_ll.cpt
[[ -s vel_ll.cpt ]] || die "vel_ll.cpt was not generated"

echo "[STEP 3] Plot the geographic velocity map with GMT"
rm -f vel_ll.pdf
gmt begin vel_ll pdf
    gmt set \
        MAP_FRAME_TYPE plain \
        FONT_ANNOT_PRIMARY 10p \
        FONT_LABEL 11p \
        FONT_TITLE 13p \
        COLOR_NAN gray
    gmt grdimage vel_ll.grd \
        -JM15c \
        -Cvel_ll.cpt \
        -Baf \
        -BWSen+t"SBAS velocity"
    gmt colorbar \
        -DJBC+w10c/0.3c+h+o0c/1.0c \
        -Cvel_ll.cpt \
        -Bxa2f1+l"Velocity (mm/yr)"
gmt end
[[ -s vel_ll.pdf ]] || die "vel_ll.pdf was not generated"

echo "[STEP 4] Generate KML products"
grd2kml.csh vel_ll vel_ll.cpt

KML_COUNT="$(find . -maxdepth 2 \( -type f -o -type l \) \
    \( -name 'vel_ll*.kml' -o -name 'vel_ll*.kmz' \) | wc -l | tr -d ' ')"
(( KML_COUNT > 0 )) || die "grd2kml.csh completed but no vel_ll KML/KMZ file was found"

{
    printf 'completed=%s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    printf 'track=%s\n' "$TRACK"
    printf 'filter_meters=%s\n' "$FILTER_METERS"
    printf 'gauss_source=%s\n' "$GAUSS_SOURCE"
    printf 'cpt_range=%s/%s/%s\n' "$CPT_MIN" "$CPT_MAX" "$CPT_STEP"
    printf 'pdf=%s\n' "$(pwd -P)/vel_ll.pdf"
    printf 'kml_files=%s\n' "$KML_COUNT"
} > run4.4_complete

echo "========================================"
echo "[DONE] Run 4.4 completed"
echo "Velocity grid   : $(pwd -P)/vel_ll.grd"
echo "Color palette   : $(pwd -P)/vel_ll.cpt"
echo "PDF map         : $(pwd -P)/vel_ll.pdf"
echo "KML/KMZ files   : $KML_COUNT"
find . -maxdepth 2 \( -type f -o -type l \) \
    \( -name 'vel_ll*.kml' -o -name 'vel_ll*.kmz' \) -print | sort
echo "========================================"
