#!/usr/bin/env bash
# Run 3.4 parallel: generate LT-1 interferograms in isolated job directories.
# Preview is the default. Add positional argument 1 to run formally.
set -euo pipefail

die() { echo "[ERROR] $*" >&2; exit 1; }

# Internal worker mode. Each pair gets a private intf/ directory so concurrent
# p2p_processing.csh processes never write to the same temporary path.
if [[ "${1:-}" == "--worker" ]]; then
    [[ $# -eq 9 ]] || die "invalid internal worker arguments"
    run_root="$2"
    root_dir="$3"
    config_file="$4"
    p2p_cmd="$5"
    log_dir="$6"
    reference="$7"
    repeat="$8"
    output_id="$9"
    log_file="$log_dir/${reference}__${repeat}.log"
    pair="${reference}:${repeat}"
    job_dir="$run_root/jobs/${reference}__${repeat}"

    mkdir -p "$job_dir" "$(dirname "$log_file")" "$root_dir/intf_all"
    trap 'rm -rf "$job_dir"' EXIT
    ln -s "$root_dir/raw" "$job_dir/raw"
    ln -s "$root_dir/SLC" "$job_dir/SLC"
    ln -s "$root_dir/topo" "$job_dir/topo"

    # Force this worker to execute only GMTSAR stage 4. Later unwrapping and
    # geocoding stages are intentionally left for their own batch scripts.
    awk '
        $1=="proc_stage" && $2=="=" {print "proc_stage = 4"; have_stage=1; next}
        $1=="skip_stage" && $2=="=" {print "skip_stage = 5,6"; have_skip=1; next}
        {print}
        END {
            if (!have_stage) print "proc_stage = 4"
            if (!have_skip) print "skip_stage = 5,6"
        }
    ' "$config_file" > "$job_dir/config.step4.txt"

    set +e
    (
        cd "$job_dir"
        "$p2p_cmd" LT1 "$reference" "$repeat" config.step4.txt
    ) > "$log_file" 2>&1
    status=$?
    set -e

    output_dir="$job_dir/intf/$output_id"
    missing_product=""
    for product in phase.grd corr.grd phasefilt.grd; do
        if [[ ! -s "$output_dir/$product" ]]; then
            missing_product="$product"
            break
        fi
    done
    if [[ "$status" -ne 0 || ! -d "$output_dir" || -n "$missing_product" ]]; then
        if [[ -n "$missing_product" ]]; then
            echo "[CHECK FAILED] Missing $missing_product" >> "$log_file"
        fi
        echo "[FAILED] $pair (log: $log_file)"
        exit 1
    fi

    mv "$output_dir" "$root_dir/intf_all/$output_id"
    echo "[DONE] $pair -> intf_all/$output_id"
    exit 0
fi

usage() {
    cat <<'HELP'
Run 3.4 parallel: LT-1 parallel interferogram generation (GMTSAR step 4)

Usage:
  run3.4_batch_interferometry_LT1_parallel.sh --master YYYYMMDD [--jobs N]
  run3.4_batch_interferometry_LT1_parallel.sh 1 --master YYYYMMDD [--jobs N]

Examples:
  ./run3.4_batch_interferometry_LT1_parallel.sh --master 20250423 --jobs 4
  ./run3.4_batch_interferometry_LT1_parallel.sh 1 --master 20250423 --jobs 4

Options:
  --master DATE   Required master date in YYYYMMDD format.
  --jobs N        Number of simultaneous interferograms (default: 4).
  --pairs FILE    Pair list generated by Run 3.3 (default: intf.list).
  --config FILE   GMTSAR configuration (default: config.LT1.txt).

Method:
  Each pair runs p2p_processing.csh LT1 REFERENCE REPEAT in a private working
  directory containing links to raw/, SLC/ and topo/. Only step 4 is enabled.
  Completed products are moved into intf_all/REFERENCE_ID_REPEAT_ID/.

Existing outputs for selected pairs are moved to
archive_run3.4_parallel/TIMESTAMP/intf_all/. Per-pair logs are retained under
run3.4_parallel_logs/TIMESTAMP/. Temporary workers run under
intf/run3.4_parallel_TIMESTAMP/ and are removed when the run finishes.

Recommendation:
  Start with --jobs 4. Large SLC files are I/O and memory intensive; using all
  CPU cores can be slower or exhaust memory.
HELP
}

formal=0
master_date=""
jobs=4
pairs_file="intf.list"
config_file="config.LT1.txt"

if [[ $# -eq 0 ]]; then
    usage
    exit 0
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage; exit 0 ;;
        1) formal=1; shift ;;
        --master)
            [[ $# -ge 2 ]] || die "--master requires YYYYMMDD"
            master_date="$2"
            shift 2
            ;;
        --jobs)
            [[ $# -ge 2 ]] || die "--jobs requires a positive integer"
            jobs="$2"
            shift 2
            ;;
        --pairs)
            [[ $# -ge 2 ]] || die "--pairs requires a file"
            pairs_file="$2"
            shift 2
            ;;
        --config)
            [[ $# -ge 2 ]] || die "--config requires a file"
            config_file="$2"
            shift 2
            ;;
        *) die "unknown argument: $1 (use --help)" ;;
    esac
done

[[ "$master_date" =~ ^[0-9]{8}$ ]] || die "--master must be YYYYMMDD"
[[ "$jobs" =~ ^[1-9][0-9]*$ ]] || die "--jobs must be a positive integer"
master_stem="LT1_${master_date}"
root_dir="$(pwd -P)"
slc_dir="$root_dir/SLC"
raw_dir="$root_dir/raw"
topo_dir="$root_dir/topo"

[[ -s "$pairs_file" ]] || die "pair list not found or empty: $pairs_file"
[[ -f "$config_file" ]] || die "configuration file not found: $config_file"
config_file="$(cd "$(dirname "$config_file")" && pwd -P)/$(basename "$config_file")"

p2p_cmd="$(command -v p2p_processing.csh || true)"
[[ -n "$p2p_cmd" ]] || die "p2p_processing.csh was not found in PATH"
command -v xargs >/dev/null 2>&1 || die "xargs was not found in PATH"

topo_phase="$(awk '$1=="topo_phase" && $2=="=" {print $3; exit}' "$config_file")"
shift_topo="$(awk '$1=="shift_topo" && $2=="=" {print $3; exit}' "$config_file")"
if [[ "$topo_phase" == "1" && "$shift_topo" == "1" ]]; then
    topo_grid="$topo_dir/topo_shift.grd"
    [[ -s "$topo_grid" ]] || die "missing topo/topo_shift.grd; Run 3.2 may be incomplete"
elif [[ "$topo_phase" == "1" ]]; then
    topo_grid="$topo_dir/topo_ra.grd"
    [[ -s "$topo_grid" ]] || die "missing topo/topo_ra.grd; Run 3.2 may be incomplete"
else
    topo_grid="NONE"
fi

validation_dir="$(mktemp -d "${TMPDIR:-/tmp}/run3.4_parallel_validate.XXXXXX")"
trap 'rm -rf "$validation_dir"' EXIT
manifest="$validation_dir/pairs.tsv"
: > "$manifest"

pair_count=0
while IFS= read -r pair || [[ -n "$pair" ]]; do
    [[ -n "$pair" ]] || continue
    [[ "$pair" != \#* ]] || continue
    [[ "$pair" =~ ^(LT1_[0-9]{8}):(LT1_[0-9]{8})$ ]] || die "invalid pair in $pairs_file: $pair"
    reference="${BASH_REMATCH[1]}"
    repeat="${BASH_REMATCH[2]}"
    [[ "$reference" != "$repeat" ]] || die "self-interferogram is not allowed: $pair"

    for stem in "$reference" "$repeat"; do
        [[ -s "$slc_dir/${stem}.PRM" ]] || die "missing SLC/${stem}.PRM"
        [[ -e "$slc_dir/${stem}.SLC" ]] || die "missing SLC/${stem}.SLC"
        [[ -e "$slc_dir/${stem}.LED" ]] || die "missing SLC/${stem}.LED"
        [[ -s "$raw_dir/${stem}.PRM" ]] || die "missing raw/${stem}.PRM"
    done

    reference_id="$(awk '$1=="SC_clock_start" && $2=="=" {printf "%d",int($3); exit}' "$raw_dir/${reference}.PRM")"
    repeat_id="$(awk '$1=="SC_clock_start" && $2=="=" {printf "%d",int($3); exit}' "$raw_dir/${repeat}.PRM")"
    [[ -n "$reference_id" && -n "$repeat_id" ]] || die "failed to read SC_clock_start for $pair"
    printf '%s\t%s\t%s_%s\n' "$reference" "$repeat" "$reference_id" "$repeat_id" >> "$manifest"
    pair_count=$((pair_count + 1))
done < "$pairs_file"

[[ "$pair_count" -gt 0 ]] || die "no valid pairs found in $pairs_file"
duplicate_pair="$(awk -F'\t' '{key=$1 FS $2} seen[key]++ {print $1 ":" $2; exit}' "$manifest")"
[[ -z "$duplicate_pair" ]] || die "duplicate pair in $pairs_file: $duplicate_pair"
duplicate_output="$(awk -F'\t' 'seen[$3]++ {print $3; exit}' "$manifest")"
[[ -z "$duplicate_output" ]] || die "multiple pairs map to the same output directory: $duplicate_output"

filter_wavelength="$(awk '$1=="filter_wavelength" && $2=="=" {print $3; exit}' "$config_file")"
range_dec="$(awk '$1=="range_dec" && $2=="=" {print $3; exit}' "$config_file")"
azimuth_dec="$(awk '$1=="azimuth_dec" && $2=="=" {print $3; exit}' "$config_file")"

# Reproduce filter.csh's internal look/decimation calculation. Invalid custom
# values are rejected before multiple expensive jobs are launched.
master_prm="$slc_dir/${master_stem}.PRM"
[[ -s "$master_prm" ]] || die "missing master PRM: $master_prm"
slc_xdim="$(awk '$1=="num_rng_bins" && $2=="=" {printf "%d",$3; exit}' "$master_prm")"
slc_ydim="$(awk '$1=="num_lines" && $2=="=" {printf "%d",$3; exit}' "$master_prm")"
prf="$(awk '$1=="PRF" && $2=="=" {print $3; exit}' "$master_prm")"
rng_samp_rate="$(awk '$1=="rng_samp_rate" && $2=="=" {print $3; exit}' "$master_prm")"
[[ "$range_dec" =~ ^[1-9][0-9]*$ ]] || die "range_dec must be a positive integer"
[[ "$azimuth_dec" =~ ^[1-9][0-9]*$ ]] || die "azimuth_dec must be a positive integer"

# Every aligned SLC in the selected network must use the same radar geometry.
# Checking only the master can miss a mixed full-frame/cropped SLC directory.
while IFS= read -r stem; do
    scene_xdim="$(awk '$1=="num_rng_bins" && $2=="=" {printf "%d",$3; exit}' "$slc_dir/${stem}.PRM")"
    scene_ydim="$(awk '$1=="num_lines" && $2=="=" {printf "%d",$3; exit}' "$slc_dir/${stem}.PRM")"
    scene_bytes="$(wc -c < "$slc_dir/${stem}.SLC" | awk '{print $1}')"
    expected_bytes=$((scene_xdim * scene_ydim * 4))
    if [[ "$scene_bytes" -ne "$expected_bytes" ]]; then
        die "$stem PRM/SLC mismatch: PRM expects ${scene_xdim}x${scene_ydim}x4 = $expected_bytes bytes, but SLC contains $scene_bytes bytes; rerun Run 3.1"
    fi
    if [[ "$scene_xdim" != "$slc_xdim" || "$scene_ydim" != "$slc_ydim" ]]; then
        die "mixed SLC dimensions: master $master_stem is ${slc_xdim}x${slc_ydim}, but $stem is ${scene_xdim}x${scene_ydim}; rerun Run 3.1 for the complete data.list, then rerun Run 3.2"
    fi
done < <(awk -F'\t' '{print $1; print $2}' "$manifest" | sort -u)

az_lks="$(awk -v p="$prf" 'BEGIN {print (p < 1000 ? 1 : 4)}')"
dec_rng="$(awk -v r="$rng_samp_rate" 'BEGIN {if (r > 110000000) print 4; else if (r > 20000000) print 2; else print 1}')"
if (( azimuth_dec % 2 != 0 )); then az_lks=1; fi
if (( range_dec % 2 != 0 )); then dec_rng=1; fi
idec=$((azimuth_dec / az_lks))
jdec=$((range_dec / dec_rng))
[[ "$idec" -ge 1 ]] || die "azimuth_dec=$azimuth_dec gives idec=0 for PRF=$prf; use 1 for single-look output or an even value >= $az_lks"
[[ "$jdec" -ge 1 ]] || die "range_dec=$range_dec gives jdec=0 for rng_samp_rate=$rng_samp_rate; use 1 for single-look output or an even value >= $dec_rng"

topo_xdim="NONE"
topo_ydim="NONE"
if [[ "$topo_grid" != "NONE" ]]; then
    command -v gmt >/dev/null 2>&1 || die "GMT was not found in PATH"
    read -r topo_xdim topo_ydim <<< "$(gmt grdinfo -Cn "$topo_grid" | awk '{printf "%d %d",$9,$10}')"
    [[ "$topo_xdim" -gt 0 && "$topo_ydim" -gt 0 ]] || die "failed to read dimensions from $topo_grid"
    if (( slc_xdim % topo_xdim != 0 || slc_ydim % topo_ydim != 0 )); then
        die "SLC size ${slc_xdim}x${slc_ydim} is incompatible with $(basename "$topo_grid") size ${topo_xdim}x${topo_ydim}; rerun Run 3.2 after the final Run 3.1 alignment/cropping"
    fi
fi

echo "========================================================================"
echo "LT-1 Run 3.4 parallel interferometry (step 4)"
echo "Mode:              $([[ "$formal" -eq 1 ]] && echo FORMAL || echo PREVIEW)"
echo "Working dir:       $root_dir"
echo "Master:            $master_stem"
echo "Pair list:         $pairs_file"
echo "Selected pairs:    $pair_count"
echo "Parallel jobs:     $jobs"
echo "Config:            $config_file"
echo "Topographic phase: ${topo_phase:-MISSING}"
echo "shift_topo:        ${shift_topo:-MISSING}"
echo "SLC dimensions:    ${slc_xdim} x ${slc_ydim}"
echo "Topo dimensions:   ${topo_xdim} x ${topo_ydim}"
echo "filter_wavelength: ${filter_wavelength:-MISSING}"
echo "range_dec:         ${range_dec:-MISSING} (filter jdec=$jdec)"
echo "azimuth_dec:       ${azimuth_dec:-MISSING} (filter idec=$idec)"
echo "Output directory:  $root_dir/intf_all"
echo "========================================================================"

if [[ "$formal" -eq 0 ]]; then
    echo "[PREVIEW] All $pair_count pairs passed the input checks; no processing was started."
    echo "[NEXT]    $0 1 --master $master_date --jobs $jobs --pairs $pairs_file --config $config_file"
    exit 0
fi

timestamp="$(date +%Y%m%dT%H%M%S)"
archive_dir="$root_dir/archive_run3.4_parallel/$timestamp/intf_all"
log_dir="$root_dir/run3.4_parallel_logs/$timestamp"
run_root="$root_dir/intf/run3.4_parallel_$timestamp"
mkdir -p "$root_dir/intf_all" "$log_dir" "$run_root/jobs"

# All matching old outputs are moved before workers start, preventing target
# collisions and keeping previous results recoverable.
archive_count=0
while IFS=$'\t' read -r reference repeat output_id; do
    old_dir="$root_dir/intf_all/$output_id"
    if [[ -d "$old_dir" ]]; then
        mkdir -p "$archive_dir"
        mv "$old_dir" "$archive_dir/"
        archive_count=$((archive_count + 1))
    fi
done < "$manifest"

if [[ "$archive_count" -gt 0 ]]; then
    echo "[ARCHIVE] Moved $archive_count existing output directory/directories to $archive_dir"
else
    echo "[ARCHIVE] No selected interferogram directory required backup."
fi

script_dir="$(cd "$(dirname "$0")" && pwd -P)"
script_path="$script_dir/$(basename "$0")"
echo "[START]   Generating $pair_count interferograms with $jobs parallel jobs"
set +e
xargs -P "$jobs" -n 3 "$script_path" --worker "$run_root" "$root_dir" "$config_file" "$p2p_cmd" "$log_dir" < "$manifest"
parallel_status=$?
set -e

# The workers remove their own job directories. Remove the empty run root as
# well so no parallel scratch folders remain after completion or failure.
rm -rf "$run_root"

missing_file="$root_dir/run3.4_parallel_missing_interferograms.tsv"
: > "$missing_file"
completed_count=0
while IFS=$'\t' read -r reference repeat output_id; do
    output_dir="$root_dir/intf_all/$output_id"
    if [[ -d "$output_dir" && -n "$(find "$output_dir" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
        completed_count=$((completed_count + 1))
    else
        printf '%s:%s\t%s\n' "$reference" "$repeat" "$log_dir/${reference}__${repeat}.log" >> "$missing_file"
    fi
done < "$manifest"

if [[ "$parallel_status" -ne 0 || "$completed_count" -ne "$pair_count" ]]; then
    missing_count=$((pair_count - completed_count))
    die "$missing_count/$pair_count interferograms failed or are missing; inspect $missing_file and $log_dir"
fi

rm -f "$missing_file"
echo "[SUCCESS] Generated $completed_count/$pair_count interferograms in $root_dir/intf_all"
echo "[LOGS]    Per-pair logs: $log_dir"
echo "[CLEANUP] Parallel temporary directories were removed."
echo "[NEXT]    Inspect phase and coherence products before phase unwrapping."
