#!/usr/bin/env bash
# Run 4.1: prepare the LT-1 detrended interferogram network for GMTSAR SBAS.

set -euo pipefail
export LC_ALL=C LANG=C LANGUAGE=C

INTF_DIR="intf_all"
SBAS_DIR="sbas_detrend"
BASELINE_SRC="baseline_table.LT1.dat"
UNWRAP_NAME="unwrap_detrend_ref_pin.grd"
CORR_SOURCE_NAME="corr.grd"
CORR_SBAS_NAME="corr_sbas.grd"

die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

usage() {
    cat <<'EOF'
Run 4.1: prepare LT-1 detrended interferograms for SBAS

Usage:
  ./run4.1_update_sbas_intf_baseline_LT1.sh
  ./run4.1_update_sbas_intf_baseline_LT1.sh 1

No arguments:
  Check the completed interferograms and baseline mapping only.

Mode 1:
  1. Accept intf_all/20*_20* pairs containing corr.grd and
     unwrap_detrend_ref_pin.grd generated by Run 3.12.
  2. Match each GMTSAR day-code directory to LT1_YYYYMMDD using
     baseline_table.LT1.dat.
  3. Create corr_sbas.grd with exactly the same grid geometry as
     unwrap_detrend_ref_pin.grd. This is required when SNAPHU used an ROI but corr.grd
     remained full-frame.
  4. Write the filtered SBAS pair and baseline tables.

Outputs:
  sbas_detrend/intflist_new
  sbas_detrend/intf.in
  sbas_detrend/baseline_table.dat
  sbas_detrend/run4.1_missing_pairs.tsv
  sbas_detrend/run4.1_complete
  intf_all/<pair>/corr_sbas.grd

No interferogram directory or original grid is deleted.
EOF
}

grid_signature() {
    gmt grdinfo "$1" -C |
        awk '{print $2, $3, $4, $5, $8, $9, $10, $11, $12}'
}

scene_for_id() {
    local id="$1"
    awk -v wanted="$id" '
        int($2)==wanted {name=$1; count++}
        END {
            if(count==1) print name
            else exit 1
        }
    ' "${BASELINE_SRC}"
}

corr_covers_unwrap() {
    local corr="$1" unwrap="$2"
    local cmeta umeta
    cmeta="$(gmt grdinfo "${corr}" -C)"
    umeta="$(gmt grdinfo "${unwrap}" -C)"
    awk -v c="${cmeta}" -v u="${umeta}" '
        function abs(v) {return v<0?-v:v}
        BEGIN {
            split(c,C," "); split(u,U," ")
            # -C columns: file W E S N zmin zmax dx dy nx ny registration
            ok=(C[2]<=U[2]+1e-8 && C[3]>=U[3]-1e-8 &&
                C[4]<=U[4]+1e-8 && C[5]>=U[5]-1e-8 &&
                abs(C[8]-U[8])<1e-8 && abs(C[9]-U[9])<1e-8 &&
                C[12]==U[12])
            exit !ok
        }
    '
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi
(( $# <= 1 )) || die "use no arguments for checking, or mode 1"
[[ $# -eq 0 || "$1" == "1" ]] || die "MODE must be 1"
FORMAL=0
(( $# == 0 )) || FORMAL=1

for command_name in awk basename find gmt sort wc; do
    command -v "${command_name}" >/dev/null 2>&1 ||
        die "required command not found: ${command_name}"
done

ROOT="$(pwd -P)"
TRACK="$(basename -- "${ROOT}")"
[[ "${TRACK}" == "Ascending" || "${TRACK}" == "Descending" ]] ||
    die "run this script in an LT-1 Ascending or Descending directory"
[[ -d "${INTF_DIR}" ]] || die "cannot find ${INTF_DIR}/"
[[ -s "${BASELINE_SRC}" ]] || die "missing or empty: ${BASELINE_SRC}; run Run 3.3 first"

TMP="$(mktemp -d)"
trap 'rm -rf -- "${TMP}"' EXIT
ALL_LIST="${TMP}/all_pairs"
VALID_LIST="${TMP}/valid_pairs"
INTF_IN="${TMP}/intf.in"
MISSING_LIST="${TMP}/missing_pairs.tsv"
USED_SCENES="${TMP}/used_scenes"
FILTERED_BASELINE="${TMP}/baseline_table.dat"
: > "${ALL_LIST}"
: > "${VALID_LIST}"
: > "${INTF_IN}"
printf 'pair\tmissing_or_invalid\n' > "${MISSING_LIST}"

while IFS= read -r -d '' path; do
    pair="$(basename -- "${path}")"
    [[ "${pair}" =~ ^[0-9]{7}_[0-9]{7}$ ]] &&
        printf '%s\n' "${pair}" >> "${ALL_LIST}"
done < <(find "${INTF_DIR}" -mindepth 1 -maxdepth 1 -type d -name '20*_*' -print0)
sort -u -o "${ALL_LIST}" "${ALL_LIST}"
[[ -s "${ALL_LIST}" ]] || die "no LT-1 interferogram directories found in ${INTF_DIR}/"

while IFS= read -r pair; do
    pair_dir="${INTF_DIR}/${pair}"
    missing=()
    [[ -s "${pair_dir}/${UNWRAP_NAME}" ]] || missing+=("${UNWRAP_NAME}")
    [[ -s "${pair_dir}/${CORR_SOURCE_NAME}" ]] || missing+=("${CORR_SOURCE_NAME}")

    ref_id="${pair%%_*}"
    rep_id="${pair##*_}"
    ref_scene=""
    rep_scene=""
    if ! ref_scene="$(scene_for_id "${ref_id}")"; then
        missing+=("baseline_mapping:${ref_id}")
    fi
    if ! rep_scene="$(scene_for_id "${rep_id}")"; then
        missing+=("baseline_mapping:${rep_id}")
    fi
    [[ "${ref_id}" != "${rep_id}" ]] || missing+=("self_pair")

    if (( ${#missing[@]} == 0 )) && ! corr_covers_unwrap "${pair_dir}/${CORR_SOURCE_NAME}" "${pair_dir}/${UNWRAP_NAME}"; then
        missing+=("corr_grid_does_not_cover_unwrap_grid")
    fi

    if (( ${#missing[@]} == 0 )); then
        printf '%s\n' "${pair}" >> "${VALID_LIST}"
        printf '%s:%s\n' "${ref_scene}" "${rep_scene}" >> "${INTF_IN}"
    else
        joined="$(IFS=,; printf '%s' "${missing[*]}")"
        printf '%s\t%s\n' "${pair}" "${joined}" >> "${MISSING_LIST}"
    fi
done < "${ALL_LIST}"

TOTAL="$(wc -l < "${ALL_LIST}" | awk '{print $1}')"
VALID="$(wc -l < "${VALID_LIST}" | awk '{print $1}')"
EXCLUDED=$(( TOTAL - VALID ))
(( VALID > 0 )) || die "no complete LT-1 interferograms are available for SBAS"

awk -F: '{print $1; print $2}' "${INTF_IN}" | sort -u > "${USED_SCENES}"
awk 'NR==FNR {used[$1]=1; next} ($1 in used)' "${USED_SCENES}" "${BASELINE_SRC}" > "${FILTERED_BASELINE}"

SCENES="$(wc -l < "${USED_SCENES}" | awk '{print $1}')"
BASELINE_ROWS="$(wc -l < "${FILTERED_BASELINE}" | awk '{print $1}')"
[[ "${SCENES}" == "${BASELINE_ROWS}" ]] ||
    die "filtered baseline table does not contain every used scene"
[[ "$(wc -l < "${INTF_IN}" | awk '{print $1}')" == "${VALID}" ]] ||
    die "intf.in line count differs from the accepted-pair count"

printf '%s\n' '========================================================================'
printf '%s\n' 'LT-1 Run 4.1 prepare detrended SBAS network'
printf 'Mode:                       %s\n' "$([[ "${FORMAL}" -eq 1 ]] && printf FORMAL || printf CHECK)"
printf 'Track:                      %s\n' "${TRACK}"
printf 'Interferogram directories:  %s\n' "${TOTAL}"
printf 'Accepted SBAS pairs:        %s\n' "${VALID}"
printf 'Excluded pairs:             %s\n' "${EXCLUDED}"
printf 'Acquisition scenes:         %s\n' "${SCENES}"
printf 'Phase input:                %s\n' "${UNWRAP_NAME}"
printf 'SBAS correlation input:     %s\n' "${CORR_SBAS_NAME}"
printf 'Baseline source:            %s\n' "${BASELINE_SRC}"
printf 'SBAS directory:             %s/\n' "${SBAS_DIR}"
printf '%s\n' '========================================================================'

if (( EXCLUDED > 0 )); then
    printf '%s\n' '[WARNING] Incomplete pairs will be excluded:'
    sed -n '1,11p' "${MISSING_LIST}"
fi

if (( FORMAL == 0 )); then
    usage
    printf '%s\n' '[CHECK ONLY] No files were created or modified.'
    exit 0
fi

printf '%s\n' '[STEP 1] Create correlation grids matching each detrended unwrap grid'
while IFS= read -r pair; do
    pair_dir="${INTF_DIR}/${pair}"
    source="${pair_dir}/${CORR_SOURCE_NAME}"
    template="${pair_dir}/${UNWRAP_NAME}"
    output="${pair_dir}/${CORR_SBAS_NAME}"
    temporary="${pair_dir}/.${CORR_SBAS_NAME}.run4.1.tmp"
    rm -f -- "${temporary}"

    if [[ "$(grid_signature "${source}")" == "$(grid_signature "${template}")" ]]; then
        cp -f -- "${source}" "${temporary}"
    else
        gmt grdsample "${source}" -R"${template}" -nn -G"${temporary}"
    fi
    [[ -s "${temporary}" ]] || die "failed to create ${CORR_SBAS_NAME} for ${pair}"
    [[ "$(grid_signature "${temporary}")" == "$(grid_signature "${template}")" ]] ||
        die "${pair}: ${CORR_SBAS_NAME} geometry does not match ${UNWRAP_NAME}"
    mv -f -- "${temporary}" "${output}"
    printf '[CORR] %s -> %s\n' "${pair}" "${CORR_SBAS_NAME}"
done < "${VALID_LIST}"

printf '%s\n' '[STEP 2] Write SBAS network and baseline tables'
mkdir -p "${SBAS_DIR}"
cp -f -- "${VALID_LIST}" "${SBAS_DIR}/intflist_new"
cp -f -- "${INTF_IN}" "${SBAS_DIR}/intf.in"
cp -f -- "${FILTERED_BASELINE}" "${SBAS_DIR}/baseline_table.dat"
cp -f -- "${MISSING_LIST}" "${SBAS_DIR}/run4.1_missing_pairs.tsv"

{
    printf 'completed=%s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    printf 'track=%s\n' "${TRACK}"
    printf 'pairs=%s\n' "${VALID}"
    printf 'excluded=%s\n' "${EXCLUDED}"
    printf 'scenes=%s\n' "${SCENES}"
    printf 'unwrap_name=%s\n' "${UNWRAP_NAME}"
    printf 'corr_name=%s\n' "${CORR_SBAS_NAME}"
    printf 'baseline_source=%s\n' "${BASELINE_SRC}"
} > "${SBAS_DIR}/run4.1_complete"

printf '%s\n' '========================================================================'
printf '[SUCCESS] Pair list:      %s/intflist_new (%s)\n' "${SBAS_DIR}" "${VALID}"
printf '[SUCCESS] SBAS intf.in:   %s/intf.in\n' "${SBAS_DIR}"
printf '[SUCCESS] Baseline table: %s/baseline_table.dat (%s)\n' "${SBAS_DIR}" "${BASELINE_ROWS}"
printf '[NEXT] ./run4.2_generate_sbas_tables_command_LT1.sh 1\n'
printf '%s\n' '========================================================================'
