#!/usr/bin/env bash
# Run 2.3: link validated burst XML/TIFF, orbit EOF files and DEM into the
# standard single-stack GMTSAR directories burst/raw and burst/topo.

set -euo pipefail

export LC_ALL=C
export LANG=C
export LANGUAGE=C

die() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

usage() {
    cat <<'EOF'
========================================
Run 2.3: link burst inputs (processing NOT started)

Usage:
  ./run2.3_link_burst_raw_topo.sh
  ./run2.3_link_burst_raw_topo.sh 1 [options]
  ./run2.3_link_burst_raw_topo.sh 2 [options]

No arguments:
  Show this guide only. No input is checked and no link is created.

Mode 1 - preview:
  Validate all inputs and display the links that will be created.
  No directory or link is created or modified.

Mode 2 - formal linking:
  Create/refresh only the input symbolic links under burst/raw and burst/topo.
  Source SAFE, TIFF, XML, EOF and DEM files are never copied or deleted.

Default inputs:
  data_burst/burst_SAFE_inventory.tsv   (from Run 2.1)
  data_burst/*.EOF                      (from Run 2.1)
  topo/dem.grd                          (from Run 2.2)

Outputs:
  burst/raw/<annotation XML links>
  burst/raw/<measurement TIFF links>
  burst/raw/<orbit EOF links>
  burst/raw/dem.grd -> topo/dem.grd
  burst/topo/dem.grd -> topo/dem.grd
  burst/burst_swath.txt
  burst/run2.3_link_inventory.tsv

Options:
  --data-dir DIR       SAFE/orbit directory (default: data_burst)
  --inventory FILE     Run 2.1 inventory
                       (default: data_burst/burst_SAFE_inventory.tsv)
  --dem FILE           DEM generated by Run 2.2 (default: topo/dem.grd)
  --unit DIR           GMTSAR burst unit directory (default: burst)
  -h, --help           Show this help

Recommended:
  ./run2.3_link_burst_raw_topo.sh 1
  ./run2.3_link_burst_raw_topo.sh 2
========================================
EOF
}

if (( $# == 0 )); then
    usage
    printf '[INFO] Nothing was checked or changed.\n'
    exit 0
fi

MODE="$1"
shift
[[ "$MODE" == 1 || "$MODE" == 2 ]] || die "MODE must be 1 (preview) or 2 (formal)"

DATA_DIR="data_burst"
INVENTORY=""
DEM="topo/dem.grd"
UNIT="burst"

while (( $# > 0 )); do
    case "$1" in
        --data-dir)
            [[ $# -ge 2 ]] || die "--data-dir requires a directory"
            DATA_DIR="$2"
            shift 2
            ;;
        --inventory)
            [[ $# -ge 2 ]] || die "--inventory requires a file"
            INVENTORY="$2"
            shift 2
            ;;
        --dem)
            [[ $# -ge 2 ]] || die "--dem requires a file"
            DEM="$2"
            shift 2
            ;;
        --unit)
            [[ $# -ge 2 ]] || die "--unit requires a directory name"
            UNIT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "unknown option: $1"
            ;;
    esac
done

[[ "$UNIT" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || die "invalid --unit name: $UNIT"

ROOT="$(pwd -P)"
TRACK="$(basename -- "$ROOT")"
[[ "$TRACK" =~ ^T[0-9]+[A-Za-z]?$ ]] ||
    die "run in a T-number track directory such as T142A (current: $ROOT)"

absolute_existing_dir() {
    local value="$1"
    if [[ "$value" = /* ]]; then
        [[ -d "$value" ]] || return 1
        (cd -- "$value" && pwd -P)
    else
        [[ -d "$ROOT/$value" ]] || return 1
        (cd -- "$ROOT/$value" && pwd -P)
    fi
}

absolute_existing_file() {
    local value="$1" directory base
    if [[ "$value" = /* ]]; then
        [[ -s "$value" ]] || return 1
        directory="$(dirname -- "$value")"
        base="$(basename -- "$value")"
    else
        [[ -s "$ROOT/$value" ]] || return 1
        directory="$(dirname -- "$ROOT/$value")"
        base="$(basename -- "$value")"
    fi
    printf '%s/%s\n' "$(cd -- "$directory" && pwd -P)" "$base"
}

DATA_ABS="$(absolute_existing_dir "$DATA_DIR")" || die "data directory not found: $DATA_DIR"
if [[ -z "$INVENTORY" ]]; then
    INVENTORY="$DATA_ABS/burst_SAFE_inventory.tsv"
fi
INVENTORY_ABS="$(absolute_existing_file "$INVENTORY")" || die "inventory missing or empty: $INVENTORY"
DEM_ABS="$(absolute_existing_file "$DEM")" || die "DEM missing or empty: $DEM; complete Run 2.2 first"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/run2.3-burst.XXXXXX")"
trap 'rm -rf -- "$TMP"' EXIT INT TERM
LINK_TABLE="$TMP/link_inventory.tsv"
ERRORS="$TMP/errors.tsv"
: > "$LINK_TABLE"
: > "$ERRORS"

header="$(head -n 1 "$INVENTORY_ABS")"
expected_header=$'date\tsatellite\tswath\tpolarization\tsafe\txml'
[[ "$header" == "$expected_header" ]] || die "unexpected Run 2.1 inventory header: $header"

while IFS=$'\t' read -r date_value satellite swath polarization safe xml; do
    [[ "$date_value" == date ]] && continue
    [[ -n "$date_value" ]] || continue

    if [[ ! -d "$safe" || ! -s "$xml" ]]; then
        printf 'MISSING_SAFE_OR_XML\t%s\t%s\t%s\n' "$date_value" "$safe" "$xml" >> "$ERRORS"
        continue
    fi
    [[ "$swath" =~ ^IW[123]$ ]] || {
        printf 'BAD_SWATH\t%s\t%s\n' "$date_value" "$swath" >> "$ERRORS"
        continue
    }
    case "$polarization" in VV|VH|HH|HV) ;; *)
        printf 'BAD_POLARIZATION\t%s\t%s\n' "$date_value" "$polarization" >> "$ERRORS"
        continue
        ;;
    esac

    swath_lower="$(printf '%s' "$swath" | tr '[:upper:]' '[:lower:]')"
    pol_lower="$(printf '%s' "$polarization" | tr '[:upper:]' '[:lower:]')"
    tiffs=()
    while IFS= read -r -d '' path; do tiffs+=("$path"); done < <(
        find "$safe/measurement" -mindepth 1 -maxdepth 1 -type f \
            \( -iname "*-${swath_lower}-slc-${pol_lower}-${date_value}t*.tiff" \
               -o -iname "*-${swath_lower}-slc-${pol_lower}-${date_value}t*.tif" \) -print0 2>/dev/null
    )
    if (( ${#tiffs[@]} != 1 )); then
        printf 'TIFF_COUNT\t%s\t%s\t%s\n' "$date_value" "${#tiffs[@]}" "$safe" >> "$ERRORS"
        continue
    fi
    [[ -s "${tiffs[0]}" ]] || {
        printf 'EMPTY_TIFF\t%s\t%s\n' "$date_value" "${tiffs[0]}" >> "$ERRORS"
        continue
    }
    printf '%s\t%s\t%s\t%s\t%s\n' \
        "$date_value" "$satellite" "$swath" "$xml" "${tiffs[0]}" >> "$LINK_TABLE"
done < "$INVENTORY_ABS"

if [[ -s "$ERRORS" ]]; then
    cat "$ERRORS" >&2
    die "burst input validation failed"
fi

sort -o "$LINK_TABLE" "$LINK_TABLE"
ACQUISITIONS="$(wc -l < "$LINK_TABLE" | awk '{print $1}')"
(( ACQUISITIONS >= 2 )) || die "at least two valid burst acquisitions are required"
DUPLICATE_DATE="$(cut -f1 "$LINK_TABLE" | uniq -d | head -n 1)"
[[ -z "$DUPLICATE_DATE" ]] || die "duplicate date in link table: $DUPLICATE_DATE"
SWATHS="$(cut -f3 "$LINK_TABLE" | sort -u)"
[[ "$(printf '%s\n' "$SWATHS" | awk 'NF{n++} END{print n+0}')" -eq 1 ]] ||
    die "inventory mixes subswaths: $(printf '%s' "$SWATHS" | tr '\n' ' ')"

EOF_LIST="$TMP/eof.list"
find "$DATA_ABS" -mindepth 1 -maxdepth 1 -type f -iname '*.EOF' -print | sort > "$EOF_LIST"
EOF_COUNT="$(wc -l < "$EOF_LIST" | awk '{print $1}')"
(( EOF_COUNT > 0 )) || die "no EOF orbit files found in $DATA_ABS; complete Run 2.1"

printf '%s\n' '========================================'
printf 'Run 2.3: link burst inputs\n'
printf 'Mode           : %s\n' "$([[ $MODE == 1 ]] && printf PREVIEW || printf FORMAL)"
printf 'Track root     : %s\n' "$ROOT"
printf 'Data directory : %s\n' "$DATA_ABS"
printf 'Inventory      : %s\n' "$INVENTORY_ABS"
printf 'Detected swath : %s\n' "$SWATHS"
printf 'Acquisitions   : %s XML + %s TIFF\n' "$ACQUISITIONS" "$ACQUISITIONS"
printf 'Orbit EOF      : %s\n' "$EOF_COUNT"
printf 'DEM            : %s\n' "$DEM_ABS"
printf 'Output raw     : %s/%s/raw\n' "$ROOT" "$UNIT"
printf 'Output topo    : %s/%s/topo\n' "$ROOT" "$UNIT"
printf '%s\n' '========================================'

printf '[LINK PLAN]\n'
printf '  XML links : %s\n' "$ACQUISITIONS"
printf '  TIFF links: %s\n' "$ACQUISITIONS"
printf '  EOF links : %s\n' "$EOF_COUNT"
printf '  DEM links : 2 (raw/dem.grd and topo/dem.grd)\n'

if [[ "$MODE" == 1 ]]; then
    printf '[PREVIEW] No directory or symbolic link was created or modified.\n'
    printf '[NEXT] ./run2.3_link_burst_raw_topo.sh 2\n'
    exit 0
fi

UNIT_DIR="$ROOT/$UNIT"
RAW_DIR="$UNIT_DIR/raw"
TOPO_DIR="$UNIT_DIR/topo"
mkdir -p -- "$RAW_DIR" "$TOPO_DIR"

remove_old_input_links() {
    local directory="$1"
    local path
    while IFS= read -r -d '' path; do
        rm -f -- "$path"
    done < <(
        find "$directory" -mindepth 1 -maxdepth 1 -type l \
            \( -iname '*.xml' -o -iname '*.tif' -o -iname '*.tiff' \
               -o -iname '*.EOF' -o -name 'dem.grd' \) -print0
    )
}

link_input() {
    local source="$1"
    local destination="$2"
    if [[ -e "$destination" && ! -L "$destination" ]]; then
        die "refusing to replace regular file: $destination"
    fi
    ln -sfn -- "$source" "$destination"
}

remove_old_input_links "$RAW_DIR"
remove_old_input_links "$TOPO_DIR"

while IFS=$'\t' read -r date_value satellite swath xml tiff; do
    link_input "$xml" "$RAW_DIR/$(basename -- "$xml")"
    link_input "$tiff" "$RAW_DIR/$(basename -- "$tiff")"
done < "$LINK_TABLE"

while IFS= read -r eof; do
    [[ -n "$eof" ]] || continue
    link_input "$eof" "$RAW_DIR/$(basename -- "$eof")"
done < "$EOF_LIST"

link_input "$DEM_ABS" "$RAW_DIR/dem.grd"
link_input "$DEM_ABS" "$TOPO_DIR/dem.grd"
printf '%s\n' "$SWATHS" > "$UNIT_DIR/burst_swath.txt"
{
    printf 'date\tsatellite\tswath\txml\ttiff\n'
    cat "$LINK_TABLE"
} > "$UNIT_DIR/run2.3_link_inventory.tsv"

BROKEN="$(find "$RAW_DIR" "$TOPO_DIR" -mindepth 1 -maxdepth 1 -type l ! -exec test -e {} \; -print | wc -l | awk '{print $1}')"
(( BROKEN == 0 )) || die "$BROKEN broken links found after linking"
RAW_XML="$(find "$RAW_DIR" -mindepth 1 -maxdepth 1 -type l -iname '*.xml' | wc -l | awk '{print $1}')"
RAW_TIFF="$(find "$RAW_DIR" -mindepth 1 -maxdepth 1 -type l \( -iname '*.tif' -o -iname '*.tiff' \) | wc -l | awk '{print $1}')"
RAW_EOF="$(find "$RAW_DIR" -mindepth 1 -maxdepth 1 -type l -iname '*.EOF' | wc -l | awk '{print $1}')"
[[ "$RAW_XML" -eq "$ACQUISITIONS" && "$RAW_TIFF" -eq "$ACQUISITIONS" && "$RAW_EOF" -eq "$EOF_COUNT" ]] ||
    die "link-count mismatch: XML=$RAW_XML, TIFF=$RAW_TIFF, EOF=$RAW_EOF"

printf '[DONE] Run 2.3 linked XML=%s, TIFF=%s, EOF=%s, DEM=2\n' \
    "$RAW_XML" "$RAW_TIFF" "$RAW_EOF"
